### ISSUE TITLE
Is the degraded performance expected when more than 3-4 avatars are glowing at the same time?

### ISSUE THREAD

**Issue by frankyvij** [apgapg/avatar_glow#16]
I would like to confirm that the performance of the scrollbar becomes really janky when more than 3-4 avatars are glowing at the same time.

**Comment by apgapg** [comment]
Hi @frankyvij Scrollbar performance might degrade(due to animation) on flutter web. But if you run the example on mobile devices or desktop you will not experience any lag.

**Comment by frankyvij** [comment]
I am actually experiencing lag on my android device (Samsung Note 9), even in release mode with 3 avatars glowing at the same time.

I am using this in ListTile where there will be some users who will glow, and others won't. So when I scroll, I see a lag. I will upload the video soon.

**Comment by apgapg** [comment]
Using in Listview with multiple ListTile having avatar_glow might lag. I will try checking this with a sample.

**Comment by sanalkv** [comment]
Any update on this ?

**Comment by apgapg** [comment]
The lag might be due to heavy animations running. When multiple are present this will cause a load on GPU. I will try finding a way to min animation load if lucky

**Comment by sanalkv** [comment]
I think the widget itself is refreshing the entire UI leading to degraded performance. I hope you are able to find a solution for it.

**Comment by Tanmoy741127** [comment]
@sanalkv the stateful widget rebuilds itself. There is no need to rebuild its parent. I think the problem is not an issue related to this package. If this avatar's parent widget rebuilds frequently, it will cause all avatars to rebuild themselves.  If the list is small try to use Column rather than listview builder. I have tested this with almost 75 avatars in a column, and no performance issue was found.
